# -------------------------------
# WorldGuardGriefFix by Overwrite
# -------------------------------

# Разрешить ли гриф поршнями?
enable-pistons: true
# Разрешить ли гриф вагонетками?
enable-minecart: true
# Разрешить ли визеру разрушать блоки в регионе?
enable-wither: true
# Разрешить ли головам визера разрушать блоки в регионе?
enable-wither-skull: true
# Разрешить ли любому энтити взрывать блоки в регионе?
enable-any-explosion: true

# Блоки на которые не распространяется гриф теми или иными способами
excluded-blocks:
  - DIAMOND_BLOCK

regions:
  example:
    x1: 1
    y1: 2
    z1: 1
    x2: 1
    y2: 2
    z2: 3